FROM node:20 as build-stage

WORKDIR /frontend

COPY package*.json ./
RUN yarn

COPY . .
RUN yarn build


FROM nginx:latest as prod-stage
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /frontend/dist /usr/share/nginx/html
