version: "3.8"

networks:
  internal-network:

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: cocktail_grid-backend:latest
        command: reflex -r '\.go$$' -s go run main.go
        volumes:
          - ./backend:/go/src/app
        ports: 
          - "8080:8080"
        networks:
          - internal-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        image: cocktail_grid-frontend:latest
        ports:
            - "80:80"
        volumes:
            - ./frontend:/app
        networks:
          - internal-network

