version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: cocktail_grid-backend:latest
        command: reflex -r '\.go$$' -s swag init && go run .
        volumes:
            - ./backend:/go/src/app
        ports:
            - "8080:8080"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: cocktail_grid-frontend:latest
        command: yarn dev
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
