/**
 * Generated by @openapi-codegen
 *
 * @version 1
 */
export type DtosCocktailDto = {
  id?: number;
  imageUrl?: string;
  title?: string;
};

export type DtosCocktailIngredientDto = {
  quantity?: number;
};

export type DtosCreateCocktailDto = {
  imageUrl?: string;
  title?: string;
};

export type DtosIngredientDto = {
  name?: string;
};

export type VmsCocktailIngredientVm = {
  cocktailId?: number;
  ingredientId?: number;
  ingredientName?: string;
  quantity?: number;
};

export type VmsCocktailVm = {
  id?: number;
  imageUrl?: string;
  title?: string;
};

export type VmsDetailedCocktailVm = {
  id?: number;
  imageUrl?: string;
  ingredients?: VmsCocktailIngredientVm[];
  title?: string;
};

export type VmsIngredientVm = {
  id?: number;
  name?: string;
};
