basePath: /
definitions:
  dtos.CocktailDto:
    properties:
      image_url:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: An API to get cocktails and ingredients
  title: CocktailGrid API
  version: "1"
paths:
  /cocktails:
    get:
      consumes:
      - application/json
      description: Retrieves all available cocktails
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.CocktailDto'
      summary: Gets all cocktails
      tags:
      - cocktails
    post:
      consumes:
      - application/json
      description: Creates a new cocktail
      parameters:
      - description: Cocktail object
        in: body
        name: cocktail
        required: true
        schema:
          $ref: '#/definitions/dtos.CocktailDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.CocktailDto'
      summary: Creates a cocktail
      tags:
      - cocktails
swagger: "2.0"
