basePath: /
definitions:
  dtos.CocktailDto:
    properties:
      image_url:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: An API to get cocktails and ingredients
  title: CocktailGrid API
  version: "1"
paths:
  /cocktails:
    get:
      consumes:
      - application/json
      description: Retrieves all available cocktails
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.CocktailDto'
      summary: Gets all cocktails
      tags:
      - cocktails
swagger: "2.0"
